"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

# inspiration
# https://gist.github.com/thoughtpolice/8f2fd36ae17cd11b8e7bd93a70e31ad6

[user]
name = "Michael Bang"
email = "mic@vbang.dk"

[aliases]
l = ["log"]
s = ["status"]
e = ["edit"]
n = ["new"]
fetch = ["git", "fetch"]
push = ["git", "push"]
pub = ["git", "push", "-r", "@", "--allow-new"]
nt = ["new", "-r", "trunk()", "-m", "WIP"]

retrunk = ["rebase", "-r", "@", "-d", "trunk()"]

# Get all open stacks of work
open = ["log", "-r", "open()"]

[revset-aliases]
wip = 'description(regex:"^\\[(wip|WIP|todo|TODO)\\]|(wip|WIP|todo|TODO):?")'
'user(x)' = 'author(x) | committer(x)'
'mine()' = 'user("hmbg@novonordisk.com") | user("mic@vbang.dk")'


# stack(x, n) is the set of mutable commits reachable from 'x', with 'n'
# parents. 'n' is often useful to customize the display and return set for
# certain operations. 'x' can be used to target the set of 'roots' to traverse,
# e.g. @ is the current stack.
'stack()' = 'stack(@)'
'stack(x)' = 'stack(x, 2)'
'stack(x, n)' = 'ancestors(reachable(x, mutable()), n)'

# The current set of "open" works. It is defined as: all stacks that are
# reachable from my working copy, or any other commit I wrote.
# n = 1, meaning that nothing from `trunk()` is included, so all resulting
# commits are mutable by definition.
'open()' = 'stack(mine() | @, 1)'


[revsets]
# By default, show all my current stacks of work.
log = 'stack(mine() | @) | trunk() | @'

[ui]
editor = "vim"
default-command = "log"
pager = { command = ["less", "-FRX"], env = { LESSCHARSET = "utf-8" } }
diff-formatter = ":git"
diff-editor = ":builtin"

